name: Provision AKS Cluster

on:
  push:
    branches:
      - main
      - master
jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash


      - name: Install Ansible and Azure dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible[azure]
          pip install msrestazure azure-mgmt-resource azure-identity
          ansible-galaxy install azure.aks

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/playbook.yml
        env:
          AZURE_CLIENT_ID: "ea0f02da-f58e-490d-89d1-7fb4dbef53a7"
          AZURE_CLIENT_SECRET: "QT98Q~XSoVgBhhRq7-X5_eZeF2N.IaxtmXwn~anY"
          AZURE_TENANT_ID: "bd7fc3cc-a630-4a2b-a6b9-d3878045c85d"
          AZURE_SUBSCRIPTION_ID: "8c35b025-ce1a-48a1-8491-b82ae7d9249e"
